import random

TIPS = [

    "Java's String pool caches literals to save memory: 'a' == 'a' is true, but new String(\"a\") == \"a\" is false.",
    "In Java, 'volatile' guarantees visibility across threads but NOT atomicity, you still need synchronization for compound actions.",
    "Java records (since Java 14) auto-generate constructors, getters, equals, hashCode, and toString for immutable data classes.",
    "Autoboxing Integer values between -128 and 127 are cached by the JVM, so Integer.valueOf(100) == Integer.valueOf(100) is true, but 200 is not.",
    "Checked exceptions must be declared or caught; unchecked exceptions (RuntimeException and subclasses) don't require this.",
    "Java's switch expressions (since Java 14) can return a value directly using 'yield' or arrow syntax, reducing boilerplate.",
    "The 'final' keyword on a variable doesn't make an object immutable, it just prevents reassignment of the reference.",
    "Java's try-with-resources automatically closes any resource implementing AutoCloseable, even if an exception is thrown.",
    "Interfaces can have default methods (since Java 8), letting you add behavior without breaking existing implementations.",
    "Enums in Java are full classes, they can have fields, constructors, and methods, not just constant names.",
    "Integer overflow in Java wraps silently instead of throwing an exception, Integer.MAX_VALUE + 1 becomes Integer.MIN_VALUE.",
    "Java's equals() and hashCode() must be overridden together, breaking this contract causes subtle bugs in HashMaps and HashSets.",
    "Varargs methods in Java are just syntactic sugar for arrays under the hood.",
    "The Optional class helps avoid null checks, but calling .get() without checking isPresent() defeats its purpose.",
    "Java's String is immutable, every 'modification' like concat or replace creates a new String object.",
    "StringBuilder is not thread-safe, use StringBuffer if you need thread safety for mutable strings (though both are rarely ideal for concurrency).",
    "Java generics use type erasure, generic type information is removed at compile time, which is why you can't do 'new T()' or check 'instanceof List<String>'.",
    "The instanceof pattern matching (since Java 16) lets you combine a type check and cast in one line.",
    "Static methods in interfaces (since Java 8) let you group utility methods with the interface they relate to.",
    "Java's Comparator.comparing() and thenComparing() let you build multi-field sort logic without writing a custom Comparator class.",

    "HashMap in Java is not thread-safe, use ConcurrentHashMap for concurrent access instead of synchronizing manually.",
    "ConcurrentHashMap achieves thread safety through lock striping, only locking small segments instead of the whole map.",
    "ExecutorService should always be shut down explicitly (shutdown() or shutdownNow()), otherwise threads may keep the JVM alive.",
    "CompletableFuture lets you chain async operations without blocking threads, using thenApply, thenCompose, and thenCombine.",
    "Deadlocks happen when two threads wait on each other's locks, always acquire locks in a consistent order to avoid this.",
    "Thread pools with a fixed size prevent resource exhaustion, but sizing them wrong can cause either idle threads or task queuing delays.",
    "The synchronized keyword locks on an object's monitor, using it on a method locks on 'this', using it on a static method locks on the class object.",
    "Atomic classes like AtomicInteger use compare-and-swap (CAS) operations instead of locks, making them faster under low contention.",
    "ThreadLocal variables give each thread its own isolated copy, useful for things like per-request context in web servers.",
    "Race conditions can exist even with 'thread-safe' collections if you perform check-then-act operations without additional synchronization.",

    "In Spring Boot, @Transactional only works on public methods called from outside the class, self-invocation bypasses the proxy.",
    "Spring beans are singletons by default, meaning one instance is shared across the whole application context unless scope is changed.",
    "@Autowired by constructor injection is generally preferred over field injection, it makes dependencies explicit and testable.",
    "Spring's @Cacheable annotation can silently cache exceptions if not configured carefully, always test cache eviction logic.",
    "Spring Boot's application.properties and application.yml can be overridden by environment variables, useful for containerized deployments.",
    "The @Value annotation in Spring injects properties directly, but @ConfigurationProperties is better for grouping related settings into a typed object.",
    "Spring Security filters run in a specific order, and misordering custom filters is a common source of authentication bugs.",
    "@RestControllerAdvice lets you centralize exception handling across all controllers instead of repeating try-catch blocks.",
    "Spring Boot actuator endpoints like /actuator/health should be secured in production, they can leak sensitive system info if left open.",
    "Bean lifecycle callbacks like @PostConstruct run after dependency injection is complete, useful for setup logic that needs injected fields.",

    "Database indexes speed up reads but slow down writes, every INSERT/UPDATE also has to update the index.",
    "Connection pooling (like HikariCP) reuses DB connections instead of opening a new one per request, a massive performance win.",
    "N+1 query problems happen when an ORM lazily loads related entities in a loop, causing hundreds of extra queries.",
    "Database transactions follow ACID properties: Atomicity, Consistency, Isolation, Durability.",
    "Composite indexes are order-sensitive, an index on (a, b) helps queries filtering by 'a' or 'a and b', but not by 'b' alone.",
    "Optimistic locking uses a version column to detect conflicting updates, avoiding the overhead of database-level locks.",
    "EXPLAIN ANALYZE (Postgres) or EXPLAIN (MySQL) shows you the actual query execution plan, essential for diagnosing slow queries.",
    "Database migrations tools like Flyway or Liquibase version-control your schema changes alongside your code.",
    "Isolation levels (Read Committed, Repeatable Read, Serializable) trade off consistency guarantees against performance and concurrency.",
    "Denormalization can improve read performance at the cost of data duplication, a common tradeoff in high-read systems.",

    "A REST API should be stateless, the server shouldn't store client session state between requests.",
    "Idempotent HTTP methods (GET, PUT, DELETE) should be safe to retry without changing the result beyond the first call.",
    "HTTP status 429 (Too Many Requests) signals rate limiting, well-designed clients should implement exponential backoff on receiving it.",
    "PATCH is meant for partial updates, while PUT typically replaces the entire resource.",
    "API versioning strategies include URL versioning (/v1/users), header versioning, and query param versioning, each with different tradeoffs.",
    "HATEOAS (Hypermedia as the Engine of Application State) is a REST maturity level where responses include links to related actions.",
    "Pagination using cursor-based tokens scales better than offset-based pagination for large, frequently-changing datasets.",
    "CORS errors happen in the browser, not the server, the server must explicitly allow cross-origin requests via response headers.",
    "gRPC uses HTTP/2 and Protocol Buffers, making it faster than REST/JSON for internal service-to-service communication.",
    "Rate limiting algorithms like token bucket and sliding window log offer different tradeoffs between burst tolerance and precision.",

    "Load balancers distribute traffic using strategies like round-robin, least connections, or IP hashing, each suited to different workloads.",
    "A message queue (like Kafka or RabbitMQ) decouples producers and consumers, letting systems handle spikes in load gracefully.",
    "The CAP theorem says a distributed system can only guarantee two of Consistency, Availability, and Partition tolerance at once.",
    "Circuit breakers prevent cascading failures by temporarily blocking calls to a failing downstream service.",
    "Horizontal scaling adds more machines, vertical scaling adds more power to an existing machine, most large systems favor horizontal scaling.",
    "Caching layers (like Redis) reduce database load, but require a cache invalidation strategy to avoid serving stale data.",
    "Eventual consistency means replicas may briefly disagree but will converge over time, common in distributed NoSQL databases.",
    "A CDN (Content Delivery Network) caches static content closer to users geographically, reducing latency.",
    "Sharding splits a database across multiple machines by a key, improving scalability but complicating cross-shard queries.",
    "Idempotency keys let clients safely retry a request (like a payment) without risking duplicate processing.",

    "The JVM has multiple garbage collector algorithms (G1, ZGC, Shenandoah), G1 has been the default since Java 9.",
    "JVM heap is divided into Young and Old generations, most objects die young, which is why generational GC is efficient.",
    "JIT (Just-In-Time) compilation converts hot bytecode paths into native machine code at runtime for performance.",
    "Memory leaks in Java usually come from lingering references (like static collections or unclosed resources), not the GC failing.",
    "Profiling tools like JFR (Java Flight Recorder) or VisualVM help diagnose CPU and memory bottlenecks without heavy overhead.",
    "The -Xmx and -Xms JVM flags set the max and initial heap size, setting them equal can avoid resize pauses in production.",
    "Class loading in Java is lazy, classes are only loaded into memory the first time they're referenced.",
    "String concatenation with '+' in a loop is inefficient because it creates a new String each time, use StringBuilder instead.",
    "Escape analysis lets the JIT allocate some objects on the stack instead of the heap, if it proves they don't escape the method scope.",
    "Thread stack size (-Xss) is separate from heap size, and too many threads with large stacks can exhaust native memory.",

    "Unit tests should test one behavior in isolation, mocking external dependencies like databases or network calls.",
    "Integration tests verify that components work together correctly, often using real (or containerized) dependencies like Testcontainers.",
    "Test coverage percentage doesn't guarantee test quality, 100% coverage can still miss important edge cases.",
    "Mockito's verify() checks that a method was called, while when()/thenReturn() stubs its return value.",
    "Flaky tests (that pass/fail inconsistently) often stem from shared state, timing issues, or unmocked external calls.",
    "The Arrange-Act-Assert pattern keeps unit tests readable: set up state, perform the action, then check the result.",
    "Static analysis tools like SonarQube or SpotBugs catch bugs and code smells before they reach code review.",
    "Dependency injection makes code more testable by letting you swap real implementations for mocks in tests.",
    "Test doubles come in types: dummy, stub, spy, mock, and fake, each serving a different testing purpose.",
    "Code coverage tools measure line/branch coverage, but mutation testing (like PIT) checks if your tests actually catch bugs.",

    "SQL injection is prevented by using parameterized queries or prepared statements, never string-concatenating user input into SQL.",
    "Passwords should be hashed with a slow, salted algorithm like bcrypt or Argon2, never stored in plaintext or with fast hashes like MD5.",
    "JWTs are signed, not encrypted by default, don't put sensitive data in the payload unless it's also encrypted.",
    "CSRF attacks exploit authenticated sessions, CSRF tokens or SameSite cookies help mitigate them.",
    "The principle of least privilege means every service or user should have only the permissions it strictly needs.",
    "Rate limiting login endpoints helps prevent brute-force password attacks.",
    "HTTPS (TLS) protects data in transit, but doesn't protect against issues like SQL injection or insecure server-side code.",
    "Input validation should happen server-side even if client-side validation exists, client checks can always be bypassed.",
    "Storing secrets (API keys, DB passwords) in code or version control is a common but serious security mistake, use a secrets manager instead.",
    "OWASP Top 10 is a regularly updated list of the most critical web application security risks, worth reviewing periodically.",

    "Logs should include correlation/trace IDs so you can follow a single request across multiple microservices.",
    "Health check endpoints should verify real dependencies (DB, cache) are reachable, not just return a static 200 OK.",
    "Feature flags let you deploy code without releasing it, decoupling deployment from release.",
    "Blue-green deployments reduce downtime by running two production environments and switching traffic between them.",
    "Structured logging (JSON logs) is far easier to query and analyze at scale than plain text log lines.",
    "Backpressure is a mechanism to prevent a fast producer from overwhelming a slower consumer in a data pipeline.",
    "The Saga pattern manages distributed transactions across microservices using a sequence of local transactions and compensations.",
    "Graceful shutdown means a service finishes in-flight requests before terminating, instead of dropping them abruptly.",
    "Observability rests on three pillars: logs, metrics, and traces, each answering a different kind of question about system behavior.",
    "A well-designed API should be backward compatible, additive changes are safe, but removing or renaming fields breaks consumers.",
]


def main():
    print(random.choice(TIPS))


if __name__ == "__main__":
    main()
